export {default as Banner} from "./Banner";
export {default as Layout} from "./Layout";
export {default as Img} from "./LazyLoadImage";
export {default as CircleRating} from "./Rating";
export {default as SwitchTabs} from "./SwitchTabs";
export {default as ContentWrapper} from "./ContentWrapper";
export {default as Carousel} from "./Carousel";
export {default as VideoPopup} from "./VideoPopup";
export {default as PlayIcon} from "./PlayIcon";
export {default as Genres} from "./Genres"